apiVersion: v1
kind: Service
metadata:
  name: svc-dev
  namespace: dev
spec:
  ports:
    - name: dev-nginx
      port: 80
      targetPort: dev-nginx-port
      protocol: TCP
#    - name: db
#      port: 9216
#      targetPort: 19216
#      protocol: TCP
  selector:
    app: dev-nginx-php
#  type: ClusterIP