apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: storage
          configMap:
            name: config
      containers:
        - name: nginx
          image: nginx:1.26.2
          ports:
            - name: nginx-port
              containerPort: 80
          volumeMounts:
            - name: storage
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf