apiVersion: v1
kind: Service
metadata:
  name: src
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - name: src
      port: 80
      targetPort: nginx-port
      protocol: TCP
  #type: LoadBalancer