apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: storage-nginx
          configMap:
            name: config-nginx
        - name: storage-php
          configMap:
            name: config-php
      containers:
        - name: nginx
          image: nginx:1.26.2
          ports:
            - name: nginx-port
              containerPort: 80
          volumeMounts:
            - name: storage-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: storage-php
              mountPath: /var/www/html/public