apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: test
spec:
  accessModes:
    #- ReadWriteMany # Требуется поддержка RWX (например, NFS)
    - ReadWriteOnce # Требуется поддержка RWO
  resources:
    requests:
      storage: 1Gi