apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-php
  namespace: test
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: pvc
      initContainers:
        - name: git-clone
          image: alpine/git
          command:
            - sh
            - -c
            - |
              rm -rf /var/www/html/*
              git clone https://github.com/dimitriytiho/kuber.git /var/www/html && \
              chmod -R 775 /var/www/html/storage && \
              chmod -R 775 /var/www/html/bootstrap/cache && \
              chown -R 33:33 /var/www/html
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      containers:
        - name: php
          image: jkaninda/laravel-php-fpm:8.2
          ports:
            - name: php-port
              containerPort: 8000
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html