apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: pvc
        - name: nginx-storage
          configMap:
            name: nginx-config
      initContainers:
        - name: init-chmod
          image: busybox:1.35
          command: [ "sh", "-c", "chown -R 101:101 /var/www/html && chmod -R 755 /var/www/html" ]
          securityContext:
            runAsUser: 0 # Запускаем от имени пользователя root для изменения владельца
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      containers:
        - name: nginx
          image: nginx:1.26.2
          ports:
            - name: nginx-port
              containerPort: 80
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
            - name: nginx-storage
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf