apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: test
spec:
  selector:
    app: php
  ports:
    - name: php
      port: 8000
      targetPort: php-port
      protocol: TCP
  type: ClusterIP