apiVersion: v1
kind: Service
metadata:
  name: src-php
  namespace: test
spec:
  selector:
    app: php-app
  ports:
    - name: src-php-port
      port: 8000
      targetPort: php-port
      protocol: TCP
  type: ClusterIP